export enum Role {
  ADMINISTRATOR = "admin",
  DIRECTOR_GENERAL_CEO = "director_general_ceo",
  GERENTE_GENERAL_COO = "gerente_general_coo",
  DIRECTORA_AREA_LEGAL = "directora_area_legal",
  COORDINADOR_LEGAL = "coordinador_legal",
  ABOGADO_REPRESENTANTE = "abogado_representante",
  ASISTENTE_LEGAL = "abogado_interno",
  REFERENTES = "asistente_legal",
  DIRECTOR_AREA_IT = "director_area_it",
  COORDINADOR_IT = "coordinador_it",
  ADMINISTRADOR_SISTEMAS = "administrador_sistemas",
  DESARROLLADOR_SOFTWARE = "desarrollador_software",
  SOPORTE_TECNICO = "soporte_tecnico",
  DIRECTORA_AREA_VENTAS = "directora_area_ventas",
  COORDINADOR_VENTAS = "coordinador_ventas",
  GERENTE_VENTAS = "gerente_ventas",
  EJECUTIVO_VENTAS = "ejecutivo_ventas",
  REPRESENTANTE_VENTAS = "representante_ventas",
  ANALISTA_VENTAS = "analista_ventas",
  DIRECTORA_AREA_MARKETING = "directora_area_marketing",
  COORDINADOR_MARKETING = "coordinador_marketing",
  DIRECTOR_MARKETING = "director_marketing",
  ESPECIALISTA_MARKETING_DIGITAL = "especialista_marketing_digital",
  DISENADOR_GRAFICO = "disenador_grafico",
  INVESTIGADOR_MERCADO = "investigador_mercado",
  GESTOR_CONTENIDOS = "gestor_contenidos",
  DIRECTORA_AREA_CONTABLE = "directora_area_contable",
  COORDINADOR_FINANCIERO = "coordinador_financiero",
  DIRECTOR_FINANCIERO = "director_financiero",
  CONTADOR_SENIOR = "contador_senior",
  ANALISTA_FINANCIERO = "analista_financiero",
  TESORERO = "tesorero",
  AUDITOR_INTERNO = "auditor_interno",
  CUSTOMER = "cliente",
  DEMANDADO = "demandado",
  INTERVINIENTE_JUICIO = "interviniente_juicio",
  ABOGADO_CONTRAPARTE = "abogado_contraparte",
  RECONOCIENTE = "reconociente",
  OFICIADO = "oficiado",
}

export const UserRoles = [
  Role.ADMINISTRATOR,
  // Nuevos
  Role.DIRECTOR_GENERAL_CEO,
  Role.GERENTE_GENERAL_COO,
  Role.DIRECTORA_AREA_LEGAL,
  Role.COORDINADOR_LEGAL,
  Role.ABOGADO_REPRESENTANTE,
  Role.ASISTENTE_LEGAL,
  Role.REFERENTES,
  Role.DIRECTOR_AREA_IT,
  Role.COORDINADOR_IT,
  Role.ADMINISTRADOR_SISTEMAS,
  Role.DESARROLLADOR_SOFTWARE,
  Role.SOPORTE_TECNICO,
  Role.DIRECTORA_AREA_VENTAS,
  Role.COORDINADOR_VENTAS,
  Role.GERENTE_VENTAS,
  Role.EJECUTIVO_VENTAS,
  Role.REPRESENTANTE_VENTAS,
  Role.ANALISTA_VENTAS,
  Role.DIRECTORA_AREA_MARKETING,
  Role.COORDINADOR_MARKETING,
  Role.DIRECTOR_MARKETING,
  Role.ESPECIALISTA_MARKETING_DIGITAL,
  Role.DISENADOR_GRAFICO,
  Role.INVESTIGADOR_MERCADO,
  Role.GESTOR_CONTENIDOS,
  Role.DIRECTORA_AREA_CONTABLE,
  Role.COORDINADOR_FINANCIERO,
  Role.DIRECTOR_FINANCIERO,
  Role.CONTADOR_SENIOR,
  Role.ANALISTA_FINANCIERO,
  Role.TESORERO,
  Role.AUDITOR_INTERNO,
  Role.CUSTOMER,
  Role.DEMANDADO,
  Role.INTERVINIENTE_JUICIO,
  Role.ABOGADO_CONTRAPARTE,
  Role.RECONOCIENTE,
  Role.OFICIADO,
];

export enum Permission {
  READ = "READ",
  WRITE = "WRITE",
  DELETE = "DELETE",
  UPDATE = "UPDATE",
}

export const UserPermissions = [
  Permission.READ,
  Permission.WRITE,
  Permission.DELETE,
  Permission.UPDATE,
];
